import { useEffect, useRef, useState } from 'react';
import Navigation from '@/components/Navigation';
import BackButton from '@/components/BackButton';
import { useLanguage } from '@/contexts/LanguageContext';
import { useWeather } from '@/hooks/useWeather';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import {
  Camera,
  MapPin,
  Clock,
  ShieldCheck,
  Download,
  AlertTriangle,
  CloudRain,
  Trash2,
  ExternalLink,
} from 'lucide-react';

interface Shot {
  id: string;
  dataUrl: string;
  takenAt: string;
  lat: number | null;
  lng: number | null;
}

/**
 * PMFBY damage evidence pack.
 *
 * Under the scheme a localised loss must be reported within 72 hours, and
 * missing that window is the single biggest cause of claim rejection — farmers
 * in patchy-network areas routinely lose valid claims to the clock rather than
 * to the facts.
 *
 * Everything needed is already in the phone: camera, GPS and a clock. This
 * captures photographs stamped with position and time, pairs them with the
 * rainfall actually recorded for that location, and produces one document the
 * farmer can hand over. No hardware, no field visit, no cost.
 */
export default function DamageReport() {
  const { tx, language } = useLanguage();
  const { daily, coords } = useWeather();
  const fileRef = useRef<HTMLInputElement>(null);

  const [shots, setShots] = useState<Shot[]>([]);
  const [crop, setCrop] = useState('');
  const [cause, setCause] = useState('');
  const [area, setArea] = useState('');
  const [pos, setPos] = useState<{ lat: number; lng: number } | null>(null);

  useEffect(() => {
    if (!navigator.geolocation) return;
    navigator.geolocation.getCurrentPosition(
      (p) => setPos({ lat: p.coords.latitude, lng: p.coords.longitude }),
      () => setPos(coords ? { lat: coords.lat, lng: coords.lon } : null),
      { timeout: 8000, enableHighAccuracy: true },
    );
  }, [coords]);

  /** Rain recorded near the loss corroborates a weather-related claim. */
  const recentRain = daily.slice(0, 3).filter((d) => d.precipitation > 10);

  const onPick = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    if (!files.length) return;

    const added = await Promise.all(
      files.map(
        (f) =>
          new Promise<Shot>((resolve) => {
            const reader = new FileReader();
            reader.onload = () =>
              resolve({
                id: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
                dataUrl: String(reader.result),
                // Stamp at capture time, not at export: the timestamp is the
                // whole point of the pack and must not drift.
                takenAt: new Date().toISOString(),
                lat: pos?.lat ?? null,
                lng: pos?.lng ?? null,
              });
            reader.readAsDataURL(f);
          }),
      ),
    );

    setShots((s) => [...s, ...added]);
    if (fileRef.current) fileRef.current.value = '';
    toast.success(
      tx('{n} photo(s) added', '{n} फोटो जोड़ी गई').replace('{n}', String(added.length)),
    );
  };

  const remove = (id: string) => setShots((s) => s.filter((x) => x.id !== id));

  const exportPack = () => {
    if (!shots.length) {
      toast.error(tx('Add at least one photo first', 'पहले कम से कम एक फोटो जोड़ें'));
      return;
    }

    const fmt = (iso: string) => new Date(iso).toLocaleString(language === 'hi' ? 'hi-IN' : 'en-IN');
    const w = window.open('', '_blank');
    if (!w) {
      toast.error(tx('Allow pop-ups to export', 'निर्यात के लिए पॉप-अप की अनुमति दें'));
      return;
    }

    // A printable page rather than a generated PDF: it needs no library, and
    // the browser's own "Save as PDF" produces the file the office wants.
    w.document.write(`<!doctype html><html><head><meta charset="utf-8">
<title>PMFBY Damage Report</title>
<style>
 body{font-family:system-ui,sans-serif;max-width:800px;margin:24px auto;padding:0 16px;color:#111}
 h1{font-size:22px;margin:0 0 4px} .sub{color:#666;font-size:13px;margin-bottom:20px}
 table{width:100%;border-collapse:collapse;margin-bottom:20px}
 td,th{border:1px solid #ddd;padding:8px;font-size:14px;text-align:left}
 th{background:#f5f5f5;width:35%}
 .shot{margin-bottom:22px;page-break-inside:avoid}
 .shot img{width:100%;border:1px solid #ddd;border-radius:6px}
 .meta{font-size:12px;color:#444;margin-top:6px}
 .note{font-size:12px;color:#666;border-top:1px solid #ddd;padding-top:12px;margin-top:24px}
</style></head><body>
<h1>PMFBY — Crop Damage Evidence</h1>
<div class="sub">Generated by BhoomiX on ${fmt(new Date().toISOString())}</div>
<table>
 <tr><th>Crop</th><td>${escapeHtml(crop) || '—'}</td></tr>
 <tr><th>Cause of loss</th><td>${escapeHtml(cause) || '—'}</td></tr>
 <tr><th>Affected area</th><td>${escapeHtml(area) || '—'}</td></tr>
 <tr><th>Location</th><td>${pos ? `${pos.lat.toFixed(6)}, ${pos.lng.toFixed(6)}` : 'Not captured'}</td></tr>
 <tr><th>Photographs</th><td>${shots.length}</td></tr>
 <tr><th>First photograph</th><td>${fmt(shots[0].takenAt)}</td></tr>
 ${
   recentRain.length
     ? `<tr><th>Recorded rainfall</th><td>${recentRain
         .map((d) => `${d.date}: ${Math.round(d.precipitation)}mm`)
         .join('<br>')}</td></tr>`
     : ''
 }
</table>
${shots
  .map(
    (s, i) => `<div class="shot">
  <img src="${s.dataUrl}" alt="Damage photograph ${i + 1}">
  <div class="meta">Photograph ${i + 1} — captured ${fmt(s.takenAt)}${
    s.lat != null ? ` — ${s.lat.toFixed(6)}, ${s.lng?.toFixed(6)}` : ''
  }</div>
</div>`,
  )
  .join('')}
<div class="note">
 Timestamps are recorded at the moment of capture within the BhoomiX app.
 Rainfall figures are from the Open-Meteo public weather service for the
 coordinates above. Submit within 72 hours of the loss.
</div>
</body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 400);
  };

  const oldest = shots.length ? new Date(shots[0].takenAt) : null;
  const hoursSince = oldest ? (Date.now() - oldest.getTime()) / 36e5 : 0;

  return (
    <div className="min-h-screen">
      <Navigation />
      <div className="px-4 pt-5 lg:px-6">
        <BackButton />
      </div>

      <div className="container mx-auto max-w-4xl px-4 pb-16 pt-8">
        <header className="mb-8">
          <h1 className="font-serif-display mb-3 text-4xl text-foreground md:text-5xl">
            {tx('Crop Damage Report', 'फसल नुकसान रिपोर्ट')}
          </h1>
          <p className="max-w-2xl text-muted-foreground">
            {tx(
              'Photograph the damage now. Under PMFBY a localised loss must be reported within 72 hours — missing that window is the most common reason claims are rejected.',
              'नुकसान की फोटो अभी लें। पीएमएफबीवाई में स्थानीय नुकसान 72 घंटे में बताना होता है — यही समय चूकना दावा खारिज होने का सबसे बड़ा कारण है।',
            )}
          </p>
        </header>

        <div className="mb-6 flex items-start gap-3 rounded-2xl border border-amber-500/40 bg-amber-500/[0.07] p-5">
          <Clock className="mt-0.5 h-5 w-5 flex-shrink-0 text-amber-500" />
          <div>
            <p className="font-semibold text-foreground">
              {tx('The 72-hour rule', '72 घंटे का नियम')}
            </p>
            <p className="mt-1 text-sm text-muted-foreground">
              {oldest
                ? tx(
                    'Your first photo was taken {h} hours ago. {left} hours remain to report.',
                    'आपकी पहली फोटो {h} घंटे पहले ली गई। बताने के लिए {left} घंटे बचे हैं।',
                  )
                    .replace('{h}', String(Math.floor(hoursSince)))
                    .replace('{left}', String(Math.max(0, Math.floor(72 - hoursSince))))
                : tx(
                    'Report to your insurer, bank, or the Krishi Rakshak helpline within 72 hours of the loss.',
                    'नुकसान के 72 घंटे के भीतर बीमा कंपनी, बैंक या कृषि रक्षक हेल्पलाइन को बताएं।',
                  )}
            </p>
          </div>
        </div>

        {/* Capture */}
        <section className="mb-6 rounded-2xl border border-border bg-card p-6">
          <h2 className="mb-4 flex items-center gap-2 text-lg font-bold text-foreground">
            <Camera className="h-5 w-5 text-primary" />
            {tx('1. Photograph the damage', '1. नुकसान की फोटो लें')}
          </h2>

          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            capture="environment"
            multiple
            onChange={onPick}
            className="hidden"
          />
          <Button onClick={() => fileRef.current?.click()} size="lg" className="mb-4 w-full sm:w-auto">
            <Camera className="mr-2 h-4 w-4" />
            {tx('Take / choose photos', 'फोटो लें / चुनें')}
          </Button>

          <p className="mb-4 flex items-center gap-2 text-sm text-muted-foreground">
            <MapPin className="h-4 w-4" />
            {pos
              ? tx('Location captured: {c}', 'स्थान दर्ज: {c}').replace(
                  '{c}',
                  `${pos.lat.toFixed(4)}, ${pos.lng.toFixed(4)}`,
                )
              : tx('Waiting for location…', 'स्थान का इंतज़ार…')}
          </p>

          {shots.length > 0 && (
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              {shots.map((s, i) => (
                <figure key={s.id} className="relative overflow-hidden rounded-xl border border-border">
                  <img src={s.dataUrl} alt="" className="aspect-square w-full object-cover" />
                  <figcaption className="bg-muted px-2 py-1.5 text-[11px] text-muted-foreground">
                    {new Date(s.takenAt).toLocaleTimeString()} · #{i + 1}
                  </figcaption>
                  <button
                    onClick={() => remove(s.id)}
                    aria-label={tx('Remove photo', 'फोटो हटाएं')}
                    className="absolute right-1.5 top-1.5 rounded-full bg-black/60 p-1.5 text-white"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </button>
                </figure>
              ))}
            </div>
          )}
        </section>

        {/* Details */}
        <section className="mb-6 rounded-2xl border border-border bg-card p-6">
          <h2 className="mb-4 text-lg font-bold text-foreground">
            {tx('2. Describe the loss', '2. नुकसान बताएं')}
          </h2>
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="crop">{tx('Crop', 'फसल')}</Label>
              <Input id="crop" value={crop} onChange={(e) => setCrop(e.target.value)} placeholder={tx('e.g. Soybean', 'जैसे सोयाबीन')} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="cause">{tx('Cause', 'कारण')}</Label>
              <Input id="cause" value={cause} onChange={(e) => setCause(e.target.value)} placeholder={tx('e.g. Hailstorm', 'जैसे ओलावृष्टि')} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="area">{tx('Area affected', 'प्रभावित क्षेत्र')}</Label>
              <Input id="area" value={area} onChange={(e) => setArea(e.target.value)} placeholder={tx('e.g. 2 acres', 'जैसे 2 एकड़')} />
            </div>
          </div>

          {recentRain.length > 0 && (
            <div className="mt-4 flex items-start gap-3 rounded-xl bg-sky-500/[0.08] p-4">
              <CloudRain className="mt-0.5 h-4 w-4 flex-shrink-0 text-sky-500" />
              <p className="text-sm text-muted-foreground">
                {tx(
                  'Rainfall recorded near you supports a weather-related claim:',
                  'आपके पास दर्ज बारिश मौसम-संबंधी दावे का समर्थन करती है:',
                )}{' '}
                {recentRain.map((d) => `${d.date} — ${Math.round(d.precipitation)}mm`).join(', ')}
              </p>
            </div>
          )}
        </section>

        {/* Export */}
        <section className="rounded-2xl border border-border bg-card p-6">
          <h2 className="mb-4 flex items-center gap-2 text-lg font-bold text-foreground">
            <ShieldCheck className="h-5 w-5 text-primary" />
            {tx('3. Save and submit', '3. सहेजें और जमा करें')}
          </h2>

          <Button onClick={exportPack} size="lg" className="mb-4 w-full sm:w-auto">
            <Download className="mr-2 h-4 w-4" />
            {tx('Create evidence document', 'सबूत दस्तावेज़ बनाएं')}
          </Button>

          <div className="flex items-start gap-3 rounded-xl bg-muted/60 p-4">
            <AlertTriangle className="mt-0.5 h-4 w-4 flex-shrink-0 text-muted-foreground" />
            <p className="text-sm text-muted-foreground">
              {tx(
                'This document supports your claim — it does not file it. Submit it to your insurer, your bank branch, or the Krishi Rakshak helpline on 14447 within 72 hours.',
                'यह दस्तावेज़ आपके दावे का समर्थन करता है — दावा दर्ज नहीं करता। इसे 72 घंटे के भीतर बीमा कंपनी, बैंक शाखा या कृषि रक्षक हेल्पलाइन 14447 पर जमा करें।',
              )}
            </p>
          </div>

          <a
            href="https://pmfby.gov.in/"
            target="_blank"
            rel="noopener noreferrer"
            className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline"
          >
            {tx('Open the PMFBY portal', 'पीएमएफबीवाई पोर्टल खोलें')}
            <ExternalLink className="h-4 w-4" />
          </a>
        </section>
      </div>
    </div>
  );
}

/** Values go into a document the farmer may hand to an office — escape them. */
function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string,
  );
}
